//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeService.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HSDbmdfEntities : DbContext
    {
        public HSDbmdfEntities()
            : base("name=HSDbmdfEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Option> Options { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<Residence> Residences { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<Residence_Option> Residence_Option { get; set; }
    }
}
