//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Residence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Residence()
        {
            this.Pictures = new HashSet<Picture>();
            this.Residence_Option = new HashSet<Residence_Option>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Short_Desc { get; set; }
        public string Long_Desc { get; set; }
        public string Street { get; set; }
        public int Number { get; set; }
        public int Zip { get; set; }
        public string City { get; set; }
        public int Capacity { get; set; }
        public bool Unactive { get; set; }
        public Nullable<System.DateTime> UnactiveOn { get; set; }
        public Nullable<System.DateTime> ScheduleDelete { get; set; }
        public bool Deleted { get; set; }
        public int MemberID { get; set; }
        public int CountryID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Picture> Pictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Residence_Option> Residence_Option { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
