//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class paystemp
    {
        public int id { get; set; }
        public int code { get; set; }
        public string alpha2 { get; set; }
        public string alpha3 { get; set; }
        public string nom_en_gb { get; set; }
        public string nom_fr_fr { get; set; }
    }
}
